<?php

	$country = [

		0 =>[
				'continent' 	=> 'Europe',
				'country' 		=> 'Andorra',
				'capital' 		=> 'Andorra la Vella',
				'language' 		=> 'ca',
				'fipsCode' 		=> 'AN',
				'area' 			=> '468.0',
				'code' 			=> 'AD',
				'currency' 		=> 'EUR',
			],

		1 =>[
				'continent' 	=> 'Asia',
				'country' 		=> 'United Arab Emirates',
				'capital' 		=> 'Abu Dhabi',
				'language' 		=> 'ar-AE,fa,en,hi,ur',
				'fipsCode' 		=> 'AE',
				'area' 			=> '82880.0',
				'code' 			=> 'AE',
				'currency' 		=> 'AED',
			],

		2 =>[			
				'continent' 	=> 'Asia',
				'country' 		=> 'Afghanistan',
				'capital' 		=> 'Kabul',
				'language' 		=> 'fa-AF,ps,uz-AF,tk',
				'fipsCode' 		=> 'AF',
				'area' 			=> '647500.0',
				'code' 			=> 'AF',
				'currency' 		=> 'AFN',
			],

		3 =>[
				
				'continent' 	=> 'North America',
				'country' 		=> 'Antigua and Barbuda',
				'capital' 		=> 'St. John\'s',
				'language' 		=> 'en-AG',
				'fipsCode' 		=> 'AC',
				'area' 			=> '443.0',
				'code' 			=> 'AG',
				'currency' 		=> 'XCD',
			],

		4 =>[
				'continent' 	=> 'North America',
				'country' 		=> 'Anguilla',
				'capital' 		=> 'The Valley',
				'language' 		=> 'en-AI',
				'fipsCode' 		=> 'AV',
				'area' 			=> '102.0',
				'code' 			=> 'AI',
				'currency' 		=> 'XCD',
			],

		5 =>[
				'continent' 	=> 'Europe',
				'country' 		=> 'Albania',
				'capital' 		=> 'Tirana',
				'language' 		=> 'sq,el',
				'fipsCode' 		=> 'AL',
				'area' 			=> '28748.0',
				'code' 			=> 'AL',
				'currency' 		=> 'ALL',
			],

		6 =>[
				'continent' 	=> 'Asia',
				'country' 		=> 'Armenia',
				'capital' 		=> 'Yerevan',
				'language' 		=> 'hy',
				'fipsCode' 		=> 'AM',
				'area' 			=> '29800.0',
				'code' 			=> 'AM',
				'currency' 		=> 'AMD',
			],

		7 =>[
				'continent' 	=> 'Africa',
				'country' 		=> 'Angola',
				'capital' 		=> 'Luanda',
				'language' 		=> 'pt-AO',
				'fipsCode' 		=> 'AO',
				'area' 			=> '1246700.0',
				'code' 			=> 'AO',
				'currency' 		=> 'AOA',
			],

		8 =>[
				'continent' 	=> 'Antarctica',
				'country' 		=> 'Antarctica',
				'capital' 		=> '',
				'language' 		=> '',
				'fipsCode' 		=> 'AY',
				'area' 			=> '1.4E7',
				'code' 			=> 'AQ',
				'currency' 		=> '',
			],

		9 => [
				'continent' 	=> 'South America',
				'country' 		=> 'Argentina',
				'capital' 		=> 'Buenos Aires',
				'language' 		=> 'es-AR,en,it,de,fr,gn',
				'fipsCode' 		=> 'AR',
				'area' 			=> '2766890.0',
				'code' 			=> 'AR',
				'currency' 		=> 'ARS',
			],

		10 =>[
				'continent' 	=> 'Oceania',
				'country' 		=> 'American Samoa',
				'capital' 		=> 'Pago Pago',
				'language' 		=> 'en-AS,sm,to',
				'fipsCode' 		=> 'AQ',
				'area' 			=> '199.0',
				'code' 			=> 'AS',
				'currency' 		=> 'USD',
			],

		11 =>[
				'continent' 	=> 'Europe',
				'country' 		=> 'Austria',
				'capital' 		=> 'Vienna',
				'language' 		=> 'de-AT,hr,hu,sl',
				'fipsCode' 		=> 'AU',
				'area' 			=> '83858.0',
				'code' 			=> 'AT',
				'currency' 		=> 'EUR',
			],

		12 =>[
				'continent' 	=> 'Oceania',
				'country' 		=> 'Australia',
				'capital' 		=> 'Canberra',
				'language' 		=> 'en-AU',
				'fipsCode' 		=> 'AS',
				'area' 			=> '7686850.0',
				'code' 			=> 'AU',
				'currency' 		=> 'AUD',
			],

		13 =>[
				'continent' 	=> 'North America',
				'country' 		=> 'Aruba',
				'capital' 		=> 'Oranjestad',
				'language' 		=> 'nl-AW,es,en',
				'fipsCode' 		=> 'AA',
				'area' 			=> '193.0',
				'code' 			=> 'AW',
				'currency' 		=> 'AWG',
			],

		14 =>[
				'continent' 	=> 'Europe',			
				'country' 		=> 'Åland',
				'capital' 		=> 'Mariehamn',
				'language' 		=> 'sv-AX',
				'fipsCode' 		=> '',
				'area' 			=> '1580.0',
				'code' 			=> 'AX',
				'currency' 		=> 'EUR',
			],

		15 =>[
				'continent' 	=> 'Asia',
				'country' 		=> 'Azerbaijan',
				'capital' 		=> 'Baku',
				'language' 		=> 'az,ru,hy',
				'fipsCode' 		=> 'AJ',
				'area' 			=> '86600.0',
				'code' 			=> 'AZ',
				'currency' 		=> 'AZN',
			],

		16 =>[
				'continent' 	=> 'Europe',
				'country' 		=> 'Bosnia and Herzegovina',
				'capital' 		=> 'Sarajevo',
				'language' 		=> 'bs,hr-BA,sr-BA',
				'fipsCode' 		=> 'BK',
				'area' 			=> '51129.0',
				'code' 			=> 'BA',
				'currency' 		=> 'BAM',
			],

		17 =>[
				'continent' 	=> 'North America',
				'country' 		=> 'Barbados',
				'capital' 		=> 'Bridgetown',
				'language' 		=> 'en-BB',
				'fipsCode' 		=> 'BB',
				'area' 			=> '431.0',
				'code' 			=> 'BB',
				'currency' 		=> 'BBD',
			],

		18 =>[
				'continent' 	=> 'Asia',
				'country' 		=> 'Bangladesh',
				'capital' 		=> 'Dhaka',
				'language' 		=> 'bn-BD,en',
				'fipsCode' 		=> 'BG',
				'area' 			=> '147570.0',
				'code' 			=> 'BD',
				'currency' 		=> 'BDT',
			],

		19 =>[
				'continent' 	=> 'Europe',
				'country' 		=> 'Belgium',
				'continent' 	=> 'EU',
				'capital' 		=> 'Brussels',
				'language' 		=> 'nl-BE,fr-BE,de-BE',
				'fipsCode' 		=> 'BE',
				'area' 			=> '30510.0',
				'code' 			=> 'BE',
				'currency' 		=> 'EUR',
			],

		20 =>[
							
				'continent' 	=> 'Africa',
				'country' 		=> 'Burkina Faso',
				'capital' 		=> 'Ouagadougou',
				'language' 		=> 'fr-BF',
				'fipsCode' 		=> 'UV',
				'area' 			=> '274200.0',
				'code' 			=> 'BF',
				'currency' 		=> 'XOF',
			],

		21 =>[
				'continent' 	=> 'Europe',
				'country' 		=> 'Bulgaria',
				'capital' 		=> 'Sofia',
				'language' 		=> 'bg,tr-BG,rom',
				'fipsCode' 		=> 'BU',
				'area' 			=> '110910.0',
				'code' 			=> 'BG',
				'currency' 		=> 'BGN',
			],

		22 =>[
				'continent' 	=> 'Asia',
				'country' 		=> 'Bahrain',
				'capital' 		=> 'Manama',
				'language' 		=> 'ar-BH,en,fa,ur',
				'fipsCode' 		=> 'BA',
				'area' 			=> '665.0',
				'code' 			=> 'BH',
				'currency' 		=> 'BHD',
			],

		23 =>[
				'continent' 	=> 'Africa',
				'country' 		=> 'Burundi',
				'capital' 		=> 'Bujumbura',
				'language' 		=> 'fr-BI,rn',
				'fipsCode' 		=> 'BY',
				'area' 			=> '27830.0',
				'code' 			=> 'BI',
				'currency' 		=> 'BIF',
			],

		24 =>[
				'continent' 	=> 'Africa',
				'country' 		=> 'Benin',
				'capital' 		=> 'Porto-Novo',
				'language' 		=> 'fr-BJ',
				'fipsCode' 		=> 'BN',
				'area' 			=> '112620.0',
				'code' 			=> 'BJ',
				'currency' 		=> 'XOF',
			],

		25 =>[
				'continent' 	=> 'North America',
				'country' 		=> 'Saint Barthélemy',
				'capital' 		=> 'Gustavia',
				'language' 		=> 'fr',
				'fipsCode' 		=> 'TB',
				'area' 			=> '21.0',
				'code' 			=> 'BL',
				'currency' 		=> 'EUR',
			],

		26 =>[
				'continent' 	=> 'North America',
				'country' 		=> 'Bermuda',
				'capital' 		=> 'Hamilton',
				'language' 		=> 'en-BM,pt',
				'fipsCode' 		=> 'BD',
				'area' 			=> '53.0',
				'code' 			=> 'BM',
				'currency' 		=> 'BMD',
			],

		27 =>[
				'continent' 	=> 'Asia',
				'country' 		=> 'Brunei',
				'capital' 		=> 'Bandar Seri Begawan',
				'language' 		=> 'ms-BN,en-BN',
				'fipsCode' 		=> 'BX',
				'area' 			=> '5770.0',
				'code' 			=> 'BN',
				'currency' 		=> 'BND',
			],

		28 =>[
				'continent' 	=> 'South America',
				'country' 		=> 'Bolivia',
				'capital' 		=> 'Sucre',
				'language' 		=> 'es-BO,qu,ay',
				'fipsCode' 		=> 'BL',
				'area' 			=> '1098580.0',
				'code' 			=> 'BO',
				'currency' 		=> 'BOB',
			],

		29 =>[
				'continent' 	=> 'North America',
				'country' 		=> 'Bonaire',
				'capital' 		=> 'Kralendijk',
				'language' 		=> 'nl,pap,en',
				'fipsCode' 		=> '',
				'area' 			=> '328.0',
				'code' 			=> 'BQ',
				'currency' 		=> 'USD',
			],

		30 =>[
				'continent' 	=> 'South America',
				'country' 		=> 'Brazil',
				'capital' 		=> 'Brasília',
				'language' 		=> 'pt-BR,es,en,fr',
				'fipsCode' 		=> 'BR',
				'area' 			=> '8511965.0',
				'code' 			=> 'BR',
				'currency' 		=> 'BRL',
			],

		31 =>[
				'continent' 	=> 'North America',
				'country' 		=> 'Bahamas',
				'capital' 		=> 'Nassau',
				'language' 		=> 'en-BS',
				'fipsCode' 		=> 'BF',
				'area' 			=> '13940.0',
				'code' 			=> 'BS',
				'currency' 		=> 'BSD',
			],

		32 =>[
				'continent' 	=> 'Asia',
				'country' 		=> 'Bhutan',
				'capital' 		=> 'Thimphu',
				'language' 		=> 'dz',
				'fipsCode' 		=> 'BT',
				'area' 			=> '47000.0',
				'code' 			=> 'BT',
				'currency' 		=> 'BTN',
			],

		33 =>[
				'continent' 	=> 'Antarctica',
				'country' 		=> 'Bouvet Island',
				'capital' 		=> '',
				'language' 		=> '',
				'fipsCode' 		=> 'BV',
				'area' 			=> '49.0',
				'code' 			=> 'BV',
				'currency' 		=> 'NOK',
			],

		34 =>[
				'continent' 	=> 'Africa',
				'country' 		=> 'Botswana',
				'capital' 		=> 'Gaborone',
				'language' 		=> 'en-BW,tn-BW',
				'fipsCode' 		=> 'BC',
				'area' 			=> '600370.0',
				'code' 			=> 'BW',
				'currency' 		=> 'BWP',
			],

		35 =>[
				'continent' 	=> 'Europe',
				'country' 		=> 'Belarus',
				'capital'	 	=> 'Minsk',
				'language' 		=> 'be,ru',
				'fipsCode' 		=> 'BO',
				'area' 			=> '207600.0',
				'code' 			=> 'BY',
				'currency' 		=> 'BYR',
			],

		36 =>[
				'continent' 	=> 'North America',
				'country' 		=> 'Belize',
				'capital' 		=> 'Belmopan',
				'language' 		=> 'en-BZ,es',
				'fipsCode' 		=> 'BH',
				'area' 			=> '22966.0',
				'code' 			=> 'BZ',
				'currency' 		=> 'BZD',
			],

		37 =>[
				'continent' 	=> 'North America',
				'country' 		=> 'Canada',
				'capital' 		=> 'Ottawa',
				'language' 		=> 'en-CA,fr-CA,iu',
				'fipsCode' 		=> 'CA',
				'area' 			=> '9984670.0',
				'code' 			=> 'CA',
				'currency' 		=> 'CAD',
			],

		38 =>[
				'continent' 	=> 'Asia',
				'country' 		=> 'Cocos [Keeling] Islands',
				'capital' 		=> 'West Island',
				'language' 		=> 'ms-CC,en',
				'fipsCode' 		=> 'CK',
				'area' 			=> '14.0',
				'code' 			=> 'CC',
				'currency' 		=> 'AUD',
			],

		39 =>[
				'continent' 	=> 'Africa',
				'country' 		=> 'Democratic Republic of the Congo',
				'capital' 		=> 'Kinshasa',
				'language' 		=> 'fr-CD,ln,kg',
				'fipsCode' 		=> 'CG',
				'area' 			=> '2345410.0',
				'code' 			=> 'CD',
				'currency' 		=> 'CDF',
			],

		40 =>[
				'continent' 	=> 'Africa',
				'country' 		=> 'Central African Republic',
				'capital' 		=> 'Bangui',
				'language' 		=> 'fr-CF,sg,ln,kg',
				'fipsCode' 		=> 'CT',
				'area' 			=> '622984.0',
				'code' 			=> 'CF',
				'currency' 		=> 'XAF',
			],

		41 =>[
				'continent' 	=> 'Africa',
				'country' 		=> 'Republic of the Congo',
				'capital' 		=> 'Brazzaville',
				'language' 		=> 'fr-CG,kg,ln-CG',
				'fipsCode' 		=> 'CF',
				'area' 			=> '342000.0',
				'code' 			=> 'CG',
				'currency' 		=> 'XAF',
			],

		42 =>[
				'continent' 	=> 'Europe',
				'country' 		=> 'Switzerland',
				'capital' 		=> 'Bern',
				'language' 		=> 'de-CH,fr-CH,it-CH,rm',
				'fipsCode' 		=> 'SZ',
				'area' 			=> '41290.0',
				'code' 			=> 'CH',
				'currency' 		=> 'CHF',
			],

		43 =>[
				'continent' 	=> 'Africa',
				'country' 		=> 'Ivory Coast',
				'capital' 		=> 'Yamoussoukro',
				'language' 		=> 'fr-CI',
				'fipsCode' 		=> 'IV',
				'area' 			=> '322460.0',
				'code' 			=> 'CI',
				'currency' 		=> 'XOF',
			],

		44 =>[
				'continent' 	=> 'Oceania',
				'country' 		=> 'Cook Islands',
				'capital' 		=> 'Avarua',
				'language' 		=> 'en-CK,mi',
				'fipsCode' 		=> 'CW',
				'area' 			=> '240.0',
				'code' 			=> 'CK',
				'currency' 		=> 'NZD',
			],

		45 =>[
				'continent' 	=> 'South America',
				'country' 		=> 'Chile',
				'capital' 		=> 'Santiago',
				'language' 		=> 'es-CL',
				'fipsCode' 		=> 'CI',
				'area' 			=> '756950.0',
				'code' 			=> 'CL',
				'currency' 		=> 'CLP',
			],

		46 =>[
				'continent' 	=> 'Africa',
				'country' 		=> 'Cameroon',
				'capital' 		=> 'Yaoundé',
				'language' 		=> 'en-CM,fr-CM',
				'fipsCode' 		=> 'CM',
				'area' 			=> '475440.0',
				'code' 			=> 'CM',
				'currency' 		=> 'XAF',
			],

		47 =>[
				'continent' 	=> 'Asia',
				'country' 		=> 'China',
				'capital' 		=> 'Beijing',
				'language' 		=> 'zh-CN,yue,wuu,dta,ug,za',
				'fipsCode' 		=> 'CH',
				'area' 			=> '9596960.0',
				'code' 			=> 'CN',
				'currency' 		=> 'CNY',
			],

		48 =>[
				'continent' 	=> 'South America',
				'country' 		=> 'Colombia',
				'capital' 		=> 'Bogotá',
				'language' 		=> 'es-CO',
				'fipsCode' 		=> 'CO',
				'area' 			=> '1138910.0',
				'code' 			=> 'CO',
				'currency' 		=> 'COP',
			],

		49 =>[
				'continent' 	=> 'North America',
				'country' 		=> 'Costa Rica',
				'capital' 		=> 'San José',
				'language' 		=> 'es-CR,en',
				'fipsCode' 		=> 'CS',
				'area' 			=> '51100.0',
				'code' 			=> 'CR',
				'currency' 		=> 'CRC',
			],

		50 =>[
				'continent' 	=> 'North America',
				'country' 		=> 'Cuba',
				'capital' 		=> 'Havana',
				'language' 		=> 'es-CU',
				'fipsCode' 		=> 'CU',
				'area' 			=> '110860.0',
				'code' 			=> 'CU',
				'currency' 		=> 'CUP',
			],

		51 =>[
				'country' 		=> 'Cape Verde',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Praia',
				'language' 		=> 'pt-CV',
				'fipsCode' 		=> 'CV',
				'area' 			=> '4033.0',
				'code' 			=> 'CV',
				'currency' 		=> 'CVE',
			],

		52 =>[
				'country' 		=> 'Curacao',
				'continent' 	=> 'North America',
				'capital' 		=> 'Willemstad',
				'language' 		=> 'nl,pap',
				'fipsCode' 		=> 'UC',
				'area' 			=> '444.0',
				'code' 			=> 'CW',
				'currency' 		=> 'ANG',
			],

		53 =>[
				'country' 		=> 'Christmas Island',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Flying Fish Cove',
				'language' 		=> 'en,zh,ms-CC',
				'fipsCode' 		=> 'KT',
				'area' 			=> '135.0',
				'code' 			=> 'CX',
				'currency' 		=> 'AUD',
			],

		54 =>[
				'country' 		=> 'Cyprus',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Nicosia',
				'language' 		=> 'el-CY,tr-CY,en',
				'fipsCode' 		=> 'CY',
				'area' 			=> '9250.0',
				'code' 			=> 'CY',
				'currency' 		=> 'EUR',
			],

		55 =>[
				'country' 		=> 'Czechia',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Prague',
				'language' 		=> 'cs,sk',
				'fipsCode' 		=> 'EZ',
				'area' 			=> '78866.0',
				'code' 			=> 'CZ',
				'currency' 		=> 'CZK',
			],

		56 =>[
				'country' 		=> 'Germany',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Berlin',
				'language' 		=> 'de',
				'fipsCode' 		=> 'GM',
				'area' 			=> '357021.0',
				'code' 			=> 'DE',
				'currency' 		=> 'EUR',
			],

		57 =>[
				'country' 		=> 'Djibouti',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Djibouti',
				'language' 		=> 'fr-DJ,ar,so-DJ,aa',
				'fipsCode' 		=> 'DJ',
				'area' 			=> '23000.0',
				'code' 			=> 'DJ',
				'currency' 		=> 'DJF',
			],

		58 =>[
				'country' 		=> 'Denmark',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Copenhagen',
				'language' 		=> 'da-DK,en,fo,de-DK',
				'fipsCode' 		=> 'DA',
				'area' 			=> '43094.0',
				'code' 			=> 'DK',
				'currency' 		=> 'DKK',
			],

		59 =>[
				'country' 		=> 'Dominica',
				'continent' 	=> 'North America',
				'capital' 		=> 'Roseau',
				'language' 		=> 'en-DM',
				'fipsCode' 		=> 'DO',
				'area' 			=> '754.0',
				'code' 			=> 'DM',
				'currency' 		=> 'XCD',
			],

		60 =>[
				'country' 		=> 'Dominican Republic',
				'continent' 	=> 'North America',
				'capital' 		=> 'Santo Domingo',
				'language' 		=> 'es-DO',
				'fipsCode' 		=> 'DR',
				'area' 			=> '48730.0',
				'code' 			=> 'DO',
				'currency' 		=> 'DOP',
			],

		61 =>[
				'country' 		=> 'Algeria',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Algiers',
				'language' 		=> 'ar-DZ',
				'fipsCode' 		=> 'AG',
				'area' 			=> '2381740.0',
				'code'	 		=> 'DZ',
				'currency' 		=> 'DZD',
			],

		62 =>[
				'country' 		=> 'Ecuador',
				'continent' 	=> 'South America',
				'capital' 		=> 'Quito',
				'language' 		=> 'es-EC',
				'area' 			=> '283560.0',
				'code' 			=> 'EC',
				'currency' 		=> 'USD',
			],

		63 =>[
				'country' 		=> 'Estonia',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Tallinn',
				'language' 		=> 'et,ru',
				'fipsCode' 		=> 'EN',
				'area' 			=> '45226.0',
				'code' 			=> 'EE',
				'currency' 		=> 'EUR',
			],

		64 =>[
				'country' 		=> 'Egypt',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Cairo',
				'language' 		=> 'ar-EG,en,fr',
				'fipsCode'	 	=> 'EG',
				'area' 			=> '1001450.0',
				'code' 			=> 'EG',
				'currency' 		=> 'EGP',
			],

		65 =>[
				'country' 		=> 'Western Sahara',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Laâyoune / El Aaiún',
				'language' 		=> 'ar,mey',
				'fipsCode' 		=> 'WI',
				'area' 			=> '266000.0',
				'code' 			=> 'EH',
				'currency' 		=> 'MAD',
			],

		66 =>[
				'country' 		=> 'Eritrea',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Asmara',
				'language' 		=> 'aa-ER,ar,tig,kun,ti-ER',
				'fipsCode' 		=> 'ER',
				'area' 			=> '121320.0',
				'code' 			=> 'ER',
				'currency' 		=> 'ERN',
			],

		67 =>[
				'country' 		=> 'Spain',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Madrid',
				'language' 		=> 'es-ES,ca,gl,eu,oc',
				'fipsCode' 		=> 'SP',
				'area' 			=> '504782.0',
				'code' 			=> 'ES',
				'currency' 		=> 'EUR',
			],

		68 =>[
				'country' 		=> 'Ethiopia',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Addis Ababa',
				'language'	 	=> 'am,en-ET,om-ET,ti-ET,so-ET,sid',
				'fipsCode' 		=> 'ET',
				'area' 			=> '1127127.0',
				'code' 			=> 'ET',
				'currency' 		=> 'ETB',
			],

		69 =>[
				'country' 		=> 'Finland',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Helsinki',
				'language' 		=> 'fi-FI,sv-FI,smn',
				'fipsCode' 		=> 'FI',
				'area' 			=> '337030.0',
				'code' 			=> 'FI',
				'currency' 		=> 'EUR',
			],

		70 =>[
				'country' 		=> 'Fiji',
				'continent' 	=> 'Oceania',
				'capital' 		=> 'Suva',
				'language' 		=> 'en-FJ,fj',
				'fipsCode' 		=> 'FJ',
				'area' 			=> '18270.0',
				'code' 			=> 'FJ',
				'currency' 		=> 'FJD',
			],

		71 =>[
				'country' 		=> 'Falkland Islands',
				'continent' 	=> 'South America',
				'capital' 		=> 'Stanley',
				'language' 		=> 'en-FK',
				'fipsCode' 		=> 'FK',
				'area' 			=> '12173.0',
				'code' 			=> 'FK',
				'currency' 		=> 'FKP',
			],

		72 =>[
				'country' 		=> 'Micronesia',
				'continent' 	=> 'Oceania',
				'capital' 		=> 'Palikir',
				'language' 		=> 'en-FM,chk,pon,yap,kos,uli,woe,nkr,kpg',
				'fipsCode' 		=> 'FM',
				'area' 			=> '702.0',
				'code' 			=> 'FM',
				'currency' 		=> 'USD',
			],

		73 =>[
				'country' 		=> 'Faroe Islands',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Tórshavn',
				'language' 		=> 'fo,da-FO',
				'fipsCode' 		=> 'FO',
				'area' 			=> '1399.0',
				'code' 			=> 'FO',
				'currency' 		=> 'DKK',
			],

		74 =>[
				'country' 		=> 'France',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Paris',
				'language' 		=> 'fr-FR,frp,br,co,ca,eu,oc',
				'fipsCode' 		=> 'FR',
				'area' 			=> '547030.0',
				'code' 			=> 'FR',
				'currency' 		=> 'EUR',
			],

		75 =>[
				'country' 		=> 'Gabon',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Libreville',
				'language' 		=> 'fr-GA',
				'fipsCode' 		=> 'GB',
				'area' 			=> '267667.0',
				'code' 			=> 'GA',
				'currency' 		=> 'XAF',
			],

		76 =>[
				'country' 		=> 'United Kingdom',
				'continent' 	=> 'Europe',
				'capital' 		=> 'London',
				'language' 		=> 'en-GB,cy-GB,gd',
				'fipsCode' 		=> 'UK',
				'area' 			=> '244820.0',
				'code' 			=> 'GB',
				'currency' 		=> 'GBP',
			],

		77 =>[
				'country' 		=> 'Grenada',
				'continent' 	=> 'North America',
				'capital' 		=> 'St. George\'s',
				'language' 		=> 'en-GD',
				'fipsCode'		=> 'GJ',
				'area' 			=> '344.0',
				'code' 			=> 'GD',
				'currency' 		=> 'XCD',
			],

		78 =>[
				'country' 		=> 'Georgia',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Tbilisi',
				'language' 		=> 'ka,ru,hy,az',
				'fipsCode' 		=> 'GG',
				'area' 			=> '69700.0',
				'code' 			=> 'GE',
				'currency' 		=> 'GEL',
			],

		79 =>[
				'country' 		=> 'French Guiana',
				'continent' 	=> 'South America',
				'capital' 		=> 'Cayenne',
				'language' 		=> 'fr-GF',
				'fipsCode' 		=> 'FG',
				'area' 			=> '91000.0',
				'code' 			=> 'GF',
				'currency' 		=> 'EUR',
			],

		80 =>[
				'country' 		=> 'Guernsey',
				'continent' 	=> 'Europe',
				'capital' 		=> 'St Peter Port',
				'language' 		=> 'en,fr',
				'fipsCode' 		=> 'GK',
				'area' 			=> '78.0',
				'code' 			=> 'GG',
				'currency' 		=> 'GBP',
			],

		81 =>[
				'country' 		=> 'Ghana',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Accra',
				'language' 		=> 'en-GH,ak,ee,tw',
				'fipsCode' 		=> 'GH',
				'area' 			=> '239460.0',
				'code' 			=> 'GH',
				'currency' 		=> 'GHS',
			],

		82 =>[
				'country' 		=> 'Gibraltar',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Gibraltar',
				'language' 		=> 'en-GI,es,it,pt',
				'fipsCode' 		=> 'GI',
				'area' 			=> '6.5',
				'code' 			=> 'GI',
				'currency' 		=> 'GIP',
			],

		83 =>[
				'country' 		=> 'Greenland',
				'continent' 	=> 'North America',
				'capital' 		=> 'Nuuk',
				'language' 		=> 'kl,da-GL,en',
				'fipsCode' 		=> 'GL',
				'area' 			=> '2166086.0',
				'code' 			=> 'GL',
				'currency' 		=> 'DKK',
			],

		84 =>[
				'country' 		=> 'Gambia',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Bathurst',
				'language' 		=> 'en-GM,mnk,wof,wo,ff',
				'fipsCode' 		=> 'GA',
				'area' 			=> '11300.0',
				'code' 			=> 'GM',
				'currency' 		=> 'GMD',
			],

		85 =>[
				'country' 		=> 'Guinea',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Conakry',
				'language' 		=> 'fr-GN',
				'fipsCode' 		=> 'GV',
				'area' 			=> '245857.0',
				'code' 			=> 'GN',
				'currency' 		=> 'GNF',
			],

		86 =>[
				'country' 		=> 'Guadeloupe',
				'continent' 	=> 'North America',
				'capital' 		=> 'Basse-Terre',
				'language' 		=> 'fr-GP',
				'fipsCode' 		=> 'GP',
				'area' 			=> '1780.0',
				'code' 			=> 'GP',
				'currency' 		=> 'EUR',
			],

		87 =>[
				'country' 		=> 'Equatorial Guinea',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Malabo',
				'language'	 	=> 'es-GQ,fr',
				'fipsCode' 		=> 'EK',
				'area' 			=> '28051.0',
				'code' 			=> 'GQ',
				'currency' 		=> 'XAF',
			],

		88 =>[
				'country' 		=> 'Greece',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Athens',
				'language' 		=> 'el-GR,en,fr',
				'fipsCode' 		=> 'GR',
				'area' 			=> '131940.0',
				'code' 			=> 'GR',
				'currency' 		=> 'EUR',
			],

		89 =>[
				'country' 		=> 'South Georgia and the South Sandwich Islands',
				'continent' 	=> 'Antarctica',
				'capital' 		=> 'Grytviken',
				'language' 		=> 'en',
				'fipsCode' 		=> 'SX',
				'area' 			=> '3903.0',
				'code' 			=> 'GS',
				'currency' 		=> 'GBP',
			],

		90 =>[
				'country' 		=> 'Guatemala',
				'continent' 	=> 'North America',
				'capital' 		=> 'Guatemala City',
				'language' 		=> 'es-GT',
				'fipsCode' 		=> 'GT',
				'area' 			=> '108890.0',
				'code' 			=> 'GT',
				'currency' 		=> 'GTQ',
			],

		91 =>[
				'country' 		=> 'Guam',
				'continent' 	=> 'Oceania',
				'capital' 		=> 'Hagåtña',
				'language' 		=> 'en-GU,ch-GU',
				'fipsCode' 		=> 'GQ',
				'area' 			=> '549.0',
				'code' 			=> 'GU',
				'currency' 		=> 'USD',
			],

		92 =>[
				'country' 		=> 'Guinea-Bissau',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Bissau',
				'language' 		=> 'pt-GW,pov',
				'fipsCode' 		=> 'PU',
				'area' 			=> '36120.0',
				'code' 			=> 'GW',
				'currency' 		=> 'XOF',
			],

		93 =>[
				'country' 		=> 'Guyana',
				'continent' 	=> 'South America',
				'capital' 		=> 'Georgetown',
				'language' 		=> 'en-GY',
				'fipsCode' 		=> 'GY',
				'area' 			=> '214970.0',
				'code' 			=> 'GY',
				'currency' 		=> 'GYD',
			],

		94 =>[
				'country' 		=> 'Hong Kong',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Hong Kong',
				'language' 		=> 'zh-HK,yue,zh,en',
				'fipsCode' 		=> 'HK',
				'area'	 		=> '1092.0',
				'code' 			=> 'HK',
				'currency' 		=> 'HKD',
			],

		95 =>[
				'country' 		=> 'Heard Island and McDonald Islands',
				'continent' 	=> 'Antarctica',
				'capital' 		=> '',
				'language' 		=> '',
				'fipsCode' 		=> 'HM',
				'area' 			=> '412.0',
				'code' 			=> 'HM',
				'currency' 		=> 'AUD',
			],

		96 =>[
				'country' 		=> 'Honduras',
				'continent' 	=> 'North America',
				'capital' 		=> 'Tegucigalpa',
				'language' 		=> 'es-HN',
				'fipsCode' 		=> 'HO',
				'area' 			=> '112090.0',
				'code' 			=> 'HN',
				'currency' 		=> 'HNL',
			],

		97 =>[
				'country' 		=> 'Croatia',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Zagreb',
				'language' 		=> 'hr-HR,sr',
				'fipsCode' 		=> 'HR',
				'area' 			=> '56542.0',
				'code' 			=> 'HR',
				'currency' 		=> 'HRK',
			],

		98 =>[
				'country' 		=> 'Haiti',
				'continent' 	=> 'North America',
				'capital' 		=> 'Port-au-Prince',
				'language' 		=> 'ht,fr-HT',
				'fipsCode' 		=> 'HA',
				'area' 			=> '27750.0',
				'code' 			=> 'HT',
				'currency' 		=> 'HTG',
			],

		99 =>[
				'country' 		=> 'Hungary',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Budapest',
				'language'		=> 'hu-HU',
				'fipsCode' 		=> 'HU',
				'area' 			=> '93030.0',
				'code' 			=> 'HU',
				'currency' 		=> 'HUF',
			],

		100 =>[
				'country' 		=> 'Indonesia',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Jakarta',
				'language' 		=> 'id,en,nl,jv',
				'fipsCode' 		=> 'ID',
				'area' 			=> '1919440.0',
				'code' 			=> 'ID',
				'currency' 		=> 'IDR',
			],

		101 =>[
				'country' 		=> 'Ireland',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Dublin',
				'language' 		=> 'en-IE,ga-IE',
				'fipsCode' 		=> 'EI',
				'area' 			=> '70280.0',
				'code' 			=> 'IE',
				'currency' 		=> 'EUR',
			],

		102 =>[
				'country' 		=> 'Israel',
				'continent' 	=> 'Asia',
				'capital' 		=> '',
				'language' 		=> 'he,ar-IL,en-IL,',
				'fipsCode' 		=> 'IS',
				'area' 			=> '20770.0',
				'code' 			=> 'IL',
				'currency' 		=> 'ILS',
			],

		103 =>[
				'country' 		=> 'Isle of Man',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Douglas',
				'language' 		=> 'en,gv',
				'fipsCode' 		=> 'IM',
				'area' 			=> '572.0',
				'code' 			=> 'IM',
				'currency' 		=> 'GBP',
			],

		104 =>[
				'country' 		=> 'India',
				'continent' 	=> 'Asia',
				'capital' 		=> 'New Delhi',
				'language' 		=> 'en-IN,hi,bn,te,mr,ta,ur,gu,kn,ml,or,pa,as,bh,sat,ks,ne,sd,kok,doi,mni,sit,sa,fr,lus,inc',
				'fipsCode' 		=> 'IN',
				'area' 			=> '3287590.0',
				'code' 			=> 'IN',
				'currency' 		=> 'INR',
			],

		105 =>[
				'country' 		=> 'British Indian Ocean Territory',
				'continent' 	=> 'Asia',
				'capital' 		=> '',
				'language' 		=> 'en-IO',
				'fipsCode' 		=> 'IO',
				'area' 			=> '60.0',
				'code' 			=> 'IO',
				'currency' 		=> 'USD',
			],

		106 =>[
				'country' 		=> 'Iraq',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Baghdad',
				'language' 		=> 'ar-IQ,ku,hy',
				'fipsCode'	 	=> 'IZ',
				'area' 			=> '437072.0',
				'code' 			=> 'IQ',
				'currency' 		=> 'IQD',
			],

		107 =>[
				'country' 		=> 'Iran',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Tehran',
				'language' 		=> 'fa-IR,ku',
				'fipsCode' 		=> 'IR',
				'area' 			=> '1648000.0',
				'code' 			=> 'IR',
				'currency' 		=> 'IRR',
			],

		108 =>[
				'country' 		=> 'Iceland',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Reykjavik',
				'language' 		=> 'is,en,de,da,sv,no',
				'fipsCode' 		=> 'IC',
				'area' 			=> '103000.0',
				'code' 			=> 'IS',
				'currency' 		=> 'ISK',
			],

		109 =>[
				'country' 		=> 'Italy',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Rome',
				'language' 		=> 'it-IT,de-IT,fr-IT,sc,ca,co,sl',
				'fipsCode' 		=> 'IT',
				'area' 			=> '301230.0',
				'code' 			=> 'IT',
				'currency' 		=> 'EUR',
			],

		110 =>[
				'country' 		=> 'Jersey',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Saint Helier',
				'language' 		=> 'en,pt',
				'fipsCode' 		=> 'JE',
				'area' 			=> '116.0',
				'code' 			=> 'JE',
				'currency' 		=> 'GBP',
			],

		111 =>[
				'country' 		=> 'Jamaica',
				'continent' 	=> 'North America',
				'capital' 		=> 'Kingston',
				'language' 		=> 'en-JM',
				'fipsCode' 		=> 'JM',
				'area' 			=> '10991.0',
				'code' 			=> 'JM',
				'currency' 		=> 'JMD',
			],

		112 =>[
				'country' 		=> 'Jordan',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Amman',
				'language' 		=> 'ar-JO,en',
				'fipsCode' 		=> 'JO',
				'area' 			=> '92300.0',
				'code' 			=> 'JO',
				'currency' 		=> 'JOD',
			],

		113 =>[
				'country' 		=> 'Japan',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Tokyo',
				'language' 		=> 'ja',
				'fipsCode' 		=> 'JA',
				'area' 			=> '377835.0',
				'code' 			=> 'JP',
				'currency' 		=> 'JPY',
			],

		114 =>[
				'country' 		=> 'Kenya',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Nairobi',
				'language' 		=> 'en-KE,sw-KE',
				'fipsCode' 		=> 'KE',
				'area' 			=> '582650.0',
				'code'	 		=> 'KE',
				'currency' 		=> 'KES',
			],

		115 =>[
				'country' 		=> 'Kyrgyzstan',
				'continent' 	=> 'Asia',
				'capital'	 	=> 'Bishkek',
				'language' 		=> 'ky,uz,ru',
				'fipsCode'	 	=> 'KG',
				'area' 			=> '198500.0',
				'code' 			=> 'KG',
				'currency' 		=> 'KGS',
			],

		116 =>[
				'country' 		=> 'Cambodia',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Phnom Penh',
				'language' 		=> 'km,fr,en',
				'fipsCode' 		=> 'CB',
				'area' 			=> '181040.0',
				'code' 			=> 'KH',
				'currency' 		=> 'KHR',
			],

		117 =>[
				'country' 		=> 'Kiribati',
				'continent' 	=> 'Oceania',
				'capital' 		=> 'Tarawa',
				'language' 		=> 'en-KI,gil',
				'fipsCode' 		=> 'KR',
				'area' 			=> '811.0',
				'code' 			=> 'KI',
				'currency' 		=> 'AUD',
			],

		118 =>[
				'country' 		=> 'Comoros',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Moroni',
				'language' 		=> 'ar,fr-KM',
				'fipsCode' 		=> 'CN',
				'area' 			=> '2170.0',
				'code' 			=> 'KM',
				'currency' 		=> 'KMF',
			],

		119 =>[
				'country' 		=> 'Saint Kitts and Nevis',
				'continent' 	=> 'North America',
				'capital' 		=> 'Basseterre',
				'language' 		=> 'en-KN',
				'fipsCode' 		=> 'SC',
				'area' 			=> '261.0',
				'code' 			=> 'KN',
				'currency' 		=> 'XCD',
			],

		120 =>[
				'country' 		=> 'North Korea',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Pyongyang',
				'language' 		=> 'ko-KP',
				'fipsCode' 		=> 'KN',
				'area' 			=> '120540.0',
				'code' 			=> 'KP',
				'currency' 		=> 'KPW',
			],

		121 =>[
				'country' 		=> 'South Korea',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Seoul',
				'language' 		=> 'ko-KR,en',
				'fipsCode' 		=> 'KS',
				'area' 			=> '98480.0',
				'code' 			=> 'KR',
				'currency' 		=> 'KRW',
			],

		122 =>[
				'country' 		=> 'Kuwait',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Kuwait City',
				'language' 		=> 'ar-KW,en',
				'fipsCode' 		=> 'KU',
				'area' 			=> '17820.0',
				'code' 			=> 'KW',
				'currency' 		=> 'KWD',
			],

		123 =>[
				'country' 		=> 'Cayman Islands',
				'continent' 	=> 'North America',
				'capital' 		=> 'George Town',
				'language' 		=> 'en-KY',
				'fipsCode' 		=> 'CJ',
				'area' 			=> '262.0',
				'code' 			=> 'KY',
				'currency' 		=> 'KYD',
			],

		124 =>[
				'country' 		=> 'Kazakhstan',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Astana',
				'language' 		=> 'kk,ru',
				'fipsCode' 		=> 'KZ',
				'area' 			=> '2717300.0',
				'code' 			=> 'KZ',
				'currency' 		=> 'KZT',
			],

		125 =>[
				'country' 		=> 'Laos',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Vientiane',
				'language' 		=> 'lo,fr,en',
				'fipsCode' 		=> 'LA',
				'area' 			=> '236800.0',
				'code' 			=> 'LA',
				'currency' 		=> 'LAK',
			],

		126 =>[
				'country' 		=> 'Lebanon',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Beirut',
				'language' 		=> 'ar-LB,fr-LB,en,hy',
				'fipsCode' 		=> 'LE',
				'area'		 	=> '10400.0',
				'code' 			=> 'LB',
				'currency' 		=> 'LBP',
			],

		127 =>[
				'country' 		=> 'Saint Lucia',
				'continent' 	=> 'North America',
				'capital' 		=> 'Castries',
				'language' 		=> 'en-LC',
				'fipsCode' 		=> 'ST',
				'area' 			=> '616.0',
				'code' 			=> 'LC',
				'currency' 		=> 'XCD',
			],

		128 =>[
				'country' 		=> 'Liechtenstein',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Vaduz',
				'language' 		=> 'de-LI',
				'fipsCode' 		=> 'LS',
				'area' 			=> '160.0',
				'code' 			=> 'LI',
				'currency' 		=> 'CHF',
			],

		129 =>[
				'country' 		=> 'Sri Lanka',
				'continent' 	=> 'Asia',
				'capital' 		=> 'Colombo',
				'language' 		=> 'si,ta,en',
				'fipsCode' 		=> 'CE',
				'area' 			=> '65610.0',
				'code' 			=> 'LK',
				'currency' 		=> 'LKR',
			],

		130 =>[
				'country' 		=> 'Liberia',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Monrovia',
				'language' 		=> 'en-LR',
				'fipsCode'	 	=> 'LI',
				'area' 			=> '111370.0',
				'code' 			=> 'LR',
				'currency' 		=> 'LRD',
			],

		131 =>[
				'country' 		=> 'Lesotho',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Maseru',
				'language' 		=> 'en-LS,st,zu,xh',
				'fipsCode' 		=> 'LT',
				'area' 			=> '30355.0',
				'code' 			=> 'LS',
				'currency' 		=> 'LSL',
			],

		132 =>[
				'country' 		=> 'Lithuania',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Vilnius',
				'language' 		=> 'lt,ru,pl',
				'fipsCode' 		=> 'LH',
				'area' 			=> '65200.0',
				'code' 			=> 'LT',
				'currency' 		=> 'EUR',
			],

		133 =>[
				'country' 		=> 'Luxembourg',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Luxembourg',
				'language' 		=> 'lb,de-LU,fr-LU',
				'fipsCode' 		=> 'LU',
				'area' 			=> '2586.0',
				'code' 			=> 'LU',
				'currency' 		=> 'EUR',
			],

		134 =>[
				'country'		=> 'Latvia',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Riga',
				'language' 		=> 'lv,ru,lt',
				'population' 	=> '2217969',
				'area' 			=> '64589.0',
				'code' 			=> 'LV',
				'currency' 		=> 'EUR',
			],

		135 =>[
				'country' 		=> 'Libya',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Tripoli',
				'language' 		=> 'ar-LY,it,en',
				'fipsCode' 		=> 'LY',
				'area' 			=> '1759540.0',
				'code' 			=> 'LY',
				'currency' 		=> 'LYD',
			],

		136 =>[
				'country' 		=> 'Morocco',
				'continent' 	=> 'Africa',
				'capital' 		=> 'Rabat',
				'language' 		=> 'ar-MA,fr',
				'fipsCode' 		=> 'MO',
				'area' 			=> '446550.0',
				'code' 			=> 'MA',
				'currency' 		=> 'MAD',
			],

		137 =>[
				'country' 		=> 'Monaco',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Monaco',
				'language' 		=> 'fr-MC,en,it',
				'fipsCode' 		=> 'MN',
				'area' 			=> '1.95',
				'code' 			=> 'MC',
				'currency' 		=> 'EUR',
			],

		138 =>[
				'country' 		=> 'Moldova',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Chişinău',
				'language' 		=> 'ro,ru,gag,tr',
				'fipsCode' 		=> 'MD',
				'area' 			=> '33843.0',
				'code' 			=> 'MD',
				'currency' 		=> 'MDL',
			],

		139 =>[
				'country' 		=> 'Montenegro',
				'continent' 	=> 'Europe',
				'capital' 		=> 'Podgorica',
				'language' 		=> 'sr,hu,bs,sq,hr,rom',
				'fipsCode' 		=> 'MJ',
				'area' 			=> '14026.0',
				'code' 			=> 'ME',
				'currency' 		=> 'EUR',
			],

		140 =>[
				'country' 		=> 'Saint Martin',
				'continent' 	=> 'North America',
				'capital' 		=> 'Marigot',
				'language' 		=> 'fr',
				'fipsCode' 		=> 'RN',
				'area' 			=> '53.0',
				'code' 			=> 'MF',
				'currency' 		=> 'EUR',
			],

		141 =>[
				'country'      => 'Madagascar',
				'continent'    => 'Africa',
				'capital'      => 'Antananarivo',
				'language'     => 'fr-MG,mg',
				'fipsCode'     => 'MA',
				'area'         => '587040.0',
				'code'         => 'MG',
				'currency'     => 'MGA',
			],

		142 =>[
				'country'      => 'Marshall Islands',
		  		'continent'    => 'Oceania',
				'capital'      => 'Majuro',
				'language'     => 'mh,en-MH',
				'fipsCode'     => 'RM',
				'area'         => '181.3',
				'code'         => 'MH',
				'currency'     => 'USD',
			],

		143 =>[
				'country'      => 'Macedonia',	
		  		'continent'    => 'Europe',
				'capital'      => 'Skopje',
				'language'     => 'mk,sq,tr,rmm,sr',
				'fipsCode'     => 'MK',
				'area'         => '25333.0',
				'code'         => 'MK',
				'currency'     => 'MKD',
			],

		144 =>[
				'country'     => 'Mali',
				'continent'   => 'Africa',
				'capital'     => 'Bamako',
				'language'    => 'fr-ML,bm',
				'fipsCode'    => 'ML',
				'area'        => '1240000.0',
				'code'        => 'ML',
				'currency'    => 'XOF',
			],

		145 =>[
				'country'     => 'Myanmar [Burma]',
				'continent'   => 'Asia',
				'capital'     => 'Naypyitaw',
				'language'    => 'my',
				'fipsCode'    => 'BM',
				'area'        => '678500.0',
				'code'        => 'MM',
				'currency'    => 'MMK',

			],

		146 =>[
				'country'    => 'Mongolia',
				'continent'  => 'Asia',
				'capital'    => 'Ulan Bator',
				'language'   => 'mn,ru',
				'fipsCode'   => 'MG',
				'area'       => '1565000.0',
				'code'       => 'MN',
				'currency'   => 'MNT',
			],

		147 =>[
				'country'   => 'Macao',
				'continent' => 'Asia',
				'capital'   => 'Macao',
				'language'  => 'zh,zh-MO,pt',
				'fipsCode'  => 'MC',
				'area'      => '254.0',
				'code'      => 'MO',
				'currency'  => 'MOP',
			],

		148 =>[
				'country'   => 'Northern Mariana Islands',
				'continent' => 'Oceania',	
				'capital'   => 'Saipan',
				'language'  => 'fil,tl,zh,ch-MP,en-MP',
				'fipsCode'  => 'CQ',
				'area'      => '477.0',
				'code'      => 'MP',
				'currency'  => 'USD',
			],

		149 =>[
				'country'   => 'Martinique',
				'continent' => 'North America',
				'capital'   => 'Fort-de-France',
				'language'  => 'fr-MQ',
				'fipsCode'  => 'MB',
				'area'      => '1100.0',
				'code'      => 'MQ',
				'currency'  => 'EUR',	
			],

		150 =>[
				'country'   => 'Mauritania',	
				'continent' => 'Africa',
				'capital'   => 'Nouakchott',
				'language'  => 'ar-MR,fuc,snk,fr,mey,wo',
				'fipsCode'  => 'MR',
				'area'      => '1030700.0',
				'code'      => 'MR',
				'currency'  => 'MRO',	
			],

		151 =>[
				'country'   => 'Montserrat',
				'continent' => 'North America',
				'capital'   => 'Plymouth',
				'language'  => 'en-MS',
				'fipsCode'  => 'MH',
				'area'      => '102.0',
				'code'      => 'MS',
				'currency'  => 'XCD',
			],

		152 =>[
				'country'   => 'Malta',
				'continent' => 'Europe',
				'capital'   => 'Valletta',
				'language'  => 'mt,en-MT',
				'fipsCode'  => 'MT',
				'area' 		=> '316.0',
				'code' 		=> 'MT',
				'currency'  => 'EUR',
			],

		153 =>[
				'country' 	=> 'Mauritius',
				'continent' => 'Africa',
				'capital' 	=> 'Port Louis',
				'language'	=> 'en-MU,bho,fr',
				'fipsCode' 	=> 'MP',
				'area' 		=> '2040.0',
				'code'	 	=> 'MU',
				'currency' 	=> 'MUR',
			],

		154 =>[
				'country' 	=> 'Maldives',
				'continent' 	=> 'Asia',
				'capital' 	=> 'Malé',
				'language' 	=> 'dv,en',
				'fipsCode' 	=> 'MV',
				'area' 		=> '300.0',
				'code' 		=> 'MV',
				'currency' 	=> 'MVR',
			],

		155 =>[
				'country'   => 'Malawi',
				'continent' => 'Africa',
				'capital' 	=> 'Lilongwe',
				'language' 	=> 'ny,yao,tum,swk',
				'fipsCode' 	=> 'MI',
				'area' 		=> '118480.0',
				'code' 		=> 'MW',
				'currency' 	=> 'MWK',
			],

		156 =>[
				'country' 	=> 'Mexico',
				'continent' => 'North America',
				'capital' 	=> 'Mexico City',
				'language' 	=> 'es-MX',
				'fipsCode' 	=> 'MX',
				'area' 		=> '1972550.0',
				'code' 		=> 'MX',
				'currency' 	=> 'MXN',
			],

		157 =>[
				'country' 	=> 'Malaysia',
				'continent' => 'Asia',	
				'capital' 	=> 'Kuala Lumpur',
				'language' 	=> 'ms-MY,en,zh,ta,te,ml,pa,th',
				'fipsCode' 	=> 'MY',
				'area' 		=> '329750.0',
				'code' 		=> 'MY',
				'currency' 	=> 'MYR',
			],

		158 =>[
				'country' 	=> 'Mozambique',
				'continent' => 'Africa',
				'capital' 	=> 'Maputo',
				'language' 	=> 'pt-MZ,vmw',
				'fipsCode' 	=> 'MZ',
				'area' 		=> '801590.0',
				'code' 		=> 'MZ',
				'currency' 	=> 'MZN',
			],

		159 =>[
				'country' 	=> 'Namibia',
				'continent' => 'Africa',
				'capital' 	=> 'Windhoek',
				'language' 	=> 'en-NA,af,de,hz,naq',
				'fipsCode' 	=> 'WA',
				'area' 		=> '825418.0',
				'code' 		=> 'NA',
				'currency' 	=> 'NAD',
			],

		160 =>[
				'country' 	=> 'New Caledonia',
				'continent' => 'Oceania',
				'capital' 	=> 'Noumea',
				'language' 	=> 'fr-NC',
				'fipsCode' 	=> 'NC',
				'area' 		=> '19060.0',
				'code' 		=> 'NC',
				'currency' 	=> 'XPF',
			],

		161 =>[
				'country' 	=> 'Niger',
				'continent' => 'Africa',
				'capital' 	=> 'Niamey',
				'language' 	=> 'fr-NE,ha,kr,dje',
				'fipsCode' 	=> 'NG',
				'area' 		=> '1267000.0',
				'code' 		=> 'NE',
				'currency' 	=> 'XOF',
			],

		162 =>[
				'country'   => 'Norfolk Island',
				'continent' => 'Oceania',
				'capital' 	=> 'Kingston',
				'language' 	=> 'en-NF',
				'fipsCode' 	=> 'NF',
				'area' 		=> '34.6',
				'code' 		=> 'NF',
				'currency' 	=> 'AUD',
			],

		163 =>[
				'country' 	=> 'Nigeria',
				'continent' => 'Africa',
				'capital' 	=> 'Abuja',
				'language' 	=> 'en-NG,ha,yo,ig,ff',
				'fipsCode' 	=> 'NI',
				'area' 		=> '923768.0',
				'code' 		=> 'NG',
				'currency' 	=> 'NGN',
			],

		164 =>[
				'country' 	=> 'Nicaragua',
				'continent' => 'North America',
				'capital' 	=> 'Managua',
				'language' 	=> 'es-NI,en',
				'fipsCode' 	=> 'NU',
				'area' 		=> '129494.0',
				'code' 		=> 'NI',
				'currency' 	=> 'NIO',
			],

		165 =>[
				'country' 	=> 'Netherlands',
				'continent' => 'Europe',
				'capital' 	=> 'Amsterdam',
				'language' 	=> 'nl-NL,fy-NL',
				'fipsCode' 	=> 'NL',
				'area' 		=> '41526.0',
				'code' 		=> 'NL',
				'currency' 	=> 'EUR',
			],

		166 =>[
				'country' 	=> 'Norway',
				'continent' => 'Europe',
				'capital' 	=> 'Oslo',
				'language' 	=> 'no,nb,nn,se,fi',
				'fipsCode' 	=> 'NO',
				'area' 		=> '324220.0',
				'code' 		=> 'NO',
				'currency' 	=> 'NOK',
			],

		167 =>[
				'country' 	=> 'Nepal',
				'continent'	=> 'Asia',
				'capital' 	=> 'Kathmandu',
				'language' 	=> 'ne,en',
				'fipsCode' 	=> 'NP',
				'area' 		=> '140800.0',
				'code' 		=> 'NP',
				'currency' 	=> 'NPR',
			],

		168 =>[
				'country' 	=> 'Nauru',
				'continent' => 'Oceania',
				'capital' 	=> 'Yaren',
				'language' 	=> 'na,en-NR',
				'fipsCode'	=> 'NR',
				'area' 		=> '21.0',
				'code' 		=> 'NR',
				'currency' 	=> 'AUD',
			],

		169 =>[
				'country' 	=> 'Niue',
				'continent' => 'Oceania',
				'capital' 	=> 'Alofi',
				'language' 	=> 'niu,en-NU',
				'fipsCode' 	=> 'NE',
				'area' 		=> '260.0',
				'code' 		=> 'NU',
				'currency' 	=> 'NZD',
			],

		170 =>[
				'country' 	=> 'New Zealand',
				'continent' => 'Oceania',
				'capital' 	=> 'Wellington',
				'language' 	=> 'en-NZ,mi',
				'fipsCode' 	=> 'NZ',
				'area' 		=> '268680.0',
				'code' 		=> 'NZ',
				'currency' 	=> 'NZD',
			],

		171 =>[
				'country' 	=> 'Oman',
				'continent' => 'Asia',
				'capital' 	=> 'Muscat',
				'language' 	=> 'ar-OM,en,bal,ur',
				'fipsCode' 	=> 'MU',
				'area' 		=> '212460.0',
				'code' 		=> 'OM',
				'currency' 	=> 'OMR',
			],

		172 =>[
				'country' 	=> 'Panama',
				'continent' => 'North America',
				'capital' 	=> 'Panama City',
				'language' 	=> 'es-PA,en',
				'fipsCode' 	=> 'PM',
				'area' 		=> '78200.0',
				'code' 		=> 'PA',
				'currency' 	=> 'PAB',
			],

		173 =>[
				'country' 	=> 'Peru',
				'continent' => 'South America',
				'capital' 	=> 'Lima',
				'language' 	=> 'es-PE,qu,ay',
				'fipsCode' 	=> 'PE',
				'area' 		=> '1285220.0',
				'code' 		=> 'PE',
				'currency' 	=> 'PEN',
			],

		174 =>[
				'country' 	=> 'French Polynesia',
				'continent' => 'Oceania',
				'capital' 	=> 'Papeete',
				'language' 	=> 'fr-PF,ty',
				'fipsCode' 	=> 'FP',
				'area' 		=> '4167.0',
				'code' 		=> 'PF',
				'currency' 	=> 'XPF',
			],

		175 =>[
				'country' 	=> 'Papua New Guinea',
				'continent' => 'Oceania',
				'capital' 	=> 'Port Moresby',
				'language' 	=> 'en-PG,ho,meu,tpi',
				'fipsCode' 	=> 'PP',
				'area' 		=> '462840.0',
				'code' 		=> 'PG',
				'currency' 	=> 'PGK',
			],

		176 =>[
				'continent' => 'AS',
				'capital' 	=> 'Manila',
				'language' 	=> 'tl,en-PH,fil',
				'fipsCode' 	=> 'RP',
				'area' 		=> '300000.0',
				'code' 		=> 'PH',
				'country' 	=> 'Philippines',
				'continent' => 'Asia',
				'currency' 	=> 'PHP',
			],

		177 =>[
				'country'	=> 'Pakistan',
				'continent' => 'Asia',
				'capital' 	=> 'Islamabad',
				'language' 	=> 'ur-PK,en-PK,pa,sd,ps,brh',
				'fipsCode' 	=> 'PK',
				'area' 		=> '803940.0',
				'code' 		=> 'PK',
				'currency' 	=> 'PKR',
			],

		178 =>[
				'country' 	=> 'Poland',
				'continent' => 'Europe',
				'capital' 	=> 'Warsaw',
				'language' 	=> 'pl',
				'fipsCode' 	=> 'PL',
				'area' 		=> '312685.0',
				'code' 		=> 'PL',
				'currency' 	=> 'PLN',
			],

		179 =>[
				'country' 	=> 'Saint Pierre and Miquelon',
				'continent' => 'North America',
				'capital' 	=> 'Saint-Pierre',
				'language' 	=> 'fr-PM',
				'fipsCode' 	=> 'SB',
				'area' 		=> '242.0',
				'code' 		=> 'PM',
				'currency' 	=> 'EUR',
			],

		180 =>[
				'country' 	=> 'Pitcairn Islands',
				'continent' => 'Oceania',	
				'capital' 	=> 'Adamstown',
				'language' 	=> 'en-PN',
				'fipsCode' 	=> 'PC',
				'area' 		=> '47.0',
				'code' 		=> 'PN',
				'currency' 	=> 'NZD',
			],

		181 =>[
				'country' 	=> 'Puerto Rico',
				'continent' => 'North America',
				'capital' 	=> 'San Juan',
				'language' 	=> 'en-PR,es-PR',
				'fipsCode' 	=> 'RQ',
				'area' 		=> '9104.0',
				'code' 		=> 'PR',
				'currency' 	=> 'USD',
			],

		182 =>[
				'country' 	=> 'Palestine',
				'continent' => 'Asia',
				'capital' 	=> '',
				'language' 	=> 'ar-PS',
				'fipsCode' 	=> 'WE',
				'area' 		=> '5970.0',
				'code' 		=> 'PS',
				'currency' 	=> 'ILS',
			],

		183 =>[
				'country' 	=> 'Portugal',
				'continent' => 'Europe',
				'capital' 	=> 'Lisbon',
				'language' 	=> 'pt-PT,mwl',
				'fipsCode' 	=> 'PO',
				'area' 		=> '92391.0',
				'code' 		=> 'PT',
				'currency' 	=> 'EUR',
			],

		184 =>[
				'country' 	=> 'Palau',
				'continent' => 'Oceania',
				'capital' 	=> 'Melekeok',
				'language' 	=> 'pau,sov,en-PW,tox,ja,fil,zh',
				'fipsCode' 	=> 'PS',
				'area' 		=> '458.0',
				'code' 		=> 'PW',
				'currency' 	=> 'USD',
			],

		185 =>[
				'country' 	=> 'Paraguay',
				'continent' => 'South America',
				'capital' 	=> 'Asunción',
				'language' 	=> 'es-PY,gn',
				'fipsCode' 	=> 'PA',
				'area' 		=> '406750.0',
				'code' 		=> 'PY',
				'currency' 	=> 'PYG',
			],

		186 =>[
				'country' 	=> 'Qatar',
				'continent' => 'Asia',
				'capital' 	=> 'Doha',
				'language' 	=> 'ar-QA,es',
				'fipsCode' 	=> 'QA',
				'area' 		=> '11437.0',
				'code' 		=> 'QA',
				'currency' 	=> 'QAR',
				],

		187 =>[
				'country' 	=> 'Réunion',
				'continent' => 'Africa',
				'capital' 	=> 'Saint-Denis',
				'language' 	=> 'fr-RE',
				'fipsCode' 	=> 'RE',
				'area' 		=> '2517.0',
				'code' 		=> 'RE',
				'currency' 	=> 'EUR',
			],

		188 =>[
				'country' 	=> 'Romania',
				'continent' => 'Europe',
				'capital' 	=> 'Bucharest',
				'language' 	=> 'ro,hu,rom',
				'fipsCode' 	=> 'RO',
				'area' 		=> '237500.0',
				'code' 		=> 'RO',
				'currency' 	=> 'RON',
			],

		189 =>[
				'country' 	=> 'Serbia',
				'continent' => 'Europe',
				'capital' 	=> 'Belgrade',
				'language' 	=> 'sr,hu,bs,rom',
				'fipsCode' 	=> 'RI',
				'area' 		=> '88361.0',
				'code' 		=> 'RS',
				'currency' 	=> 'RSD',
			],

		190 =>[
				'country' 	=> 'Russia',
				'continent' => 'Europe',
				'capital' 	=> 'Moscow',
				'language' 	=> 'ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,tut,kbd,krc,ava,sah,nog',
				'fipsCode' 	=> 'RS',
				'area' 		=> '1.71E7',
				'code' 		=> 'RU',
				'currency' 	=> 'RUB',
			],

		191 =>[
				'country' 	=> 'Rwanda',
				'continent' => 'Africa',
				'capital' 	=> 'Kigali',
				'language' 	=> 'rw,en-RW,fr-RW,sw',
				'fipsCode' 	=> 'RW',
				'area' 		=> '26338.0',
				'code' 		=> 'RW',
				'currency' 	=> 'RWF',
			],

		192 =>[
				'country' 	=> 'Saudi Arabia',
				'continent' => 'Asia',
				'capital' 	=> 'Riyadh',
				'language' 	=> 'ar-SA',
				'fipsCode' 	=> 'SA',
				'area' 		=> '1960582.0',
				'code' 		=> 'SA',
				'currency' 	=> 'SAR',
			],

		193 =>[
				'country' 	=> 'Solomon Islands',
				'continent' => 'Oceania',
				'capital' 	=> 'Honiara',
				'language' 	=> 'en-SB,tpi',
				'fipsCode' 	=> 'BP',
				'area' 		=> '28450.0',
				'code' 		=> 'SB',
				'currency' 	=> 'SBD',
			],

		194 =>[
				'country' 	=> 'Seychelles',
				'continent' => 'Africa',
				'capital' 	=> 'Victoria',
				'language' 	=> 'en-SC,fr-SC',
				'fipsCode' 	=> 'SE',
				'area' 		=> '455.0',
				'code' 		=> 'SC',
				'currency' 	=> 'SCR',
			],

		195 =>[
				'country' 	=> 'Sudan',
				'continent' => 'Africa',
				'capital' 	=> 'Khartoum',
				'language' 	=> 'ar-SD,en,fia',
				'fipsCode' 	=> 'SU',
				'area' 		=> '1861484.0',
				'code' 		=> 'SD',
				'currency' 	=> 'SDG',
			],

		196 =>[
				'country' 	=> 'Sweden',
				'continent' => 'Europe',
				'capital' 	=> 'Stockholm',
				'language' 	=> 'sv-SE,se,sma,fi-SE',
				'fipsCode' 	=> 'SW',
				'area' 		=> '449964.0',
				'code' 		=> 'SE',
				'currency' 	=> 'SEK',
			],

		197 =>[
				'country' 	=> 'Singapore',
				'continent' => 'Asia',
				'capital' 	=> 'Singapore',
				'language' 	=> 'cmn,en-SG,ms-SG,ta-SG,zh-SG',
				'fipsCode' 	=> 'SN',
				'area' 		=> '692.7',
				'code' 		=> 'SG',
				'currency' 	=> 'SGD',
			],

		198 =>[
				'country' 	=> 'Saint Helena',
				'continent' => 'Africa',
				'capital' 	=> 'Jamestown',
				'language' 	=> 'en-SH',
				'fipsCode' 	=> 'SH',
				'area' 		=> '410.0',
				'code' 		=> 'SH',
				'currency' 	=> 'SHP',
			],

		199 =>[
				'country' 	=> 'Slovenia',
				'continent' => 'Europe',
				'capital' 	=> 'Ljubljana',
				'language' 	=> 'sl,sh',
				'fipsCode' 	=> 'SI',
				'area' 		=> '20273.0',
				'code' 		=> 'SI',
				'currency' 	=> 'EUR',
			],

		200 =>[
				'country' 	=> 'Svalbard and Jan Mayen',
				'continent' => 'Europe',
				'capital' 	=> 'Longyearbyen',
				'language' 	=> 'no,ru',
				'fipsCode' 	=> 'SV',
				'area' 		=> '62049.0',
				'code' 		=> 'SJ',
				'currency' 	=> 'NOK',
			],

		201 =>[
				'country' 	=> 'Slovakia',
				'continent' => 'Europe',
				'capital' 	=> 'Bratislava',
				'language' 	=> 'sk,hu',
				'fipsCode' 	=> 'LO',
				'area' 		=> '48845.0',
				'code' 		=> 'SK',
				'currency' 	=> 'EUR',
			],

		202 =>[
				'country' 	=> 'Sierra Leone',
				'continent' => 'Africa',
				'capital' 	=> 'Freetown',
				'language' 	=> 'en-SL,men,tem',
				'fipsCode' 	=> 'SL',
				'area' 		=> '71740.0',
				'code' 		=> 'SL',
				'currency' 	=> 'SLL',
			],

		203 =>[
				'country' 	=> 'San Marino',
				'continent' => 'Europe',
				'capital' 	=> 'San Marino',
				'language' 	=> 'it-SM',
				'fipsCode' 	=> 'SM',
				'area' 		=> '61.2',
				'code' 		=> 'SM',
				'currency' 	=> 'EUR',
			],

		204 =>[
				'country' 	=> 'Senegal',
				'continent' => 'Africa',
				'capital' 	=> 'Dakar',
				'language' 	=> 'fr-SN,wo,fuc,mnk',
				'fipsCode' 	=> 'SG',
				'area' 		=> '196190.0',
				'code' 		=> 'SN',
				'currency' 	=> 'XOF',
			],

		205 =>[
				'country' 	=> 'Somalia',
				'continent' => 'Africa',
				'capital' 	=> 'Mogadishu',
				'language' 	=> 'so-SO,ar-SO,it,en-SO',
				'fipsCode' 	=> 'SO',
				'area' 		=> '637657.0',
				'code' 		=> 'SO',
				'currency' 	=> 'SOS',
			],

		206 =>[
				'country' 	=> 'Suriname',
				'continent' => 'South America',
				'capital' 	=> 'Paramaribo',
				'language' 	=> 'nl-SR,en,srn,hns,jv',
				'fipsCode' 	=> 'NS',
				'area' 		=> '163270.0',
				'code' 		=> 'SR',
				'currency' 	=> 'SRD',
			],

		207 =>[
				'country' 	=> 'South Sudan',
				'continent' => 'Africa',
				'capital' 	=> 'Juba',
				'language' 	=> 'en',
				'fipsCode' 	=> 'OD',
				'area' 		=> '644329.0',
				'code' 		=> 'SS',
				'currency' 	=> 'SSP',
			],

		208 =>[
				'country' 	=> 'São Tomé and Príncipe',
				'continent' => 'Africa',
				'capital' 	=> 'São Tomé',
				'language' 	=> 'pt-ST',
				'fipsCode' 	=> 'TP',
				'area' 		=> '1001.0',
				'code' 		=> 'ST',
				'currency' 	=> 'STD',
			],

		209 =>[
				'country' 	=> 'El Salvador',
				'continent' => 'North America',
				'capital' 	=> 'San Salvador',
				'language' 	=> 'es-SV',
				'fipsCode' 	=> 'ES',
				'area' 		=> '21040.0',
				'code' 		=> 'SV',
				'currency' 	=> 'USD',
			],

		210 =>[
				'country' 	=> 'Sint Maarten',
				'continent' => 'North America',
				'capital' 	=> 'Philipsburg',
				'language' 	=> 'nl,en',
				'fipsCode' 	=> 'NN',
				'area' 		=> '21.0',
				'code' 		=> 'SX',
				'currency' 	=> 'ANG',
			],

		211 =>[
				'country' 	=> 'Syria',
				'continent' => 'Asia',
				'capital' 	=> 'Damascus',
				'language' 	=> 'ar-SY,ku,hy,arc,fr,en',
				'fipsCode' 	=> 'SY',
				'area' 		=> '185180.0',
				'code' 		=> 'SY',
				'currency' 	=> 'SYP',
			],

		212 =>[
				'country' 	=> 'Swaziland',
				'continent' => 'Africa',
				'capital' 	=> 'Mbabane',
				'language' 	=> 'en-SZ,ss-SZ',
				'fipsCode' 	=> 'WZ',
				'area' 		=> '17363.0',
				'code' 		=> 'SZ',
				'currency' 	=> 'SZL',
			],

		213 =>[
				'country' 	=> 'Turks and Caicos Islands',
				'continent' => 'North America',
				'capital' 	=> 'Cockburn Town',
				'language' 	=> 'en-TC',
				'fipsCode' 	=> 'TK',
				'area' 		=> '430.0',
				'code' 		=> 'TC',
				'currency' 	=> 'USD',
			],

		214 =>[
				'country' 	=> 'Chad',
				'continent' => 'Africa',
				'capital' 	=> 'N\'Djamena',
				'language' 	=> 'fr-TD,ar-TD,sre',
				'fipsCode' 	=> 'CD',
				'area' 		=> '1284000.0',
				'code' 		=> 'TD',
				'currency' 	=> 'XAF',
			],

		215 =>[
				'country' 	=> 'French Southern Territories',
				'continent' => 'Antarctica',
				'capital' 	=> 'Port-aux-Français',
				'language' 	=> 'fr',
				'fipsCode' 	=> 'FS',
				'area' 		=> '7829.0',
				'code' 		=> 'TF',
				'currency' 	=> 'EUR',
			],

		216 =>[
				'country' 	=> 'Togo',
				'continent' => 'Africa',
				'capital' 	=> 'Lomé',
				'language' 	=> 'fr-TG,ee,hna,kbp,dag,ha',
				'fipsCode' 	=> 'TO',
				'area' 		=> '56785.0',
				'code' 		=> 'TG',
				'currency' 	=> 'XOF',
			],

		217 =>[
				'country' 	=> 'Thailand',
				'continent' => 'Asia',
				'capital' 	=> 'Bangkok',
				'language' 	=> 'th,en',
				'fipsCode' 	=> 'TH',
				'area' 		=> '514000.0',
				'code' 		=> 'TH',
				'currency' 	=> 'THB',
			],

		218 =>[
				'country' 	=> 'Tajikistan',
				'continent' => 'Asia',
				'capital' 	=> 'Dushanbe',
				'language' 	=> 'tg,ru',
				'fipsCode' 	=> 'TI',
				'area' 		=> '143100.0',
				'code' 		=> 'TJ',
				'currency' 	=> 'TJS',
			],

		219 =>[
				'country' 	=> 'Tokelau',
				'continent' => 'Oceania',
				'capital' 	=> '',
				'language' 	=> 'tkl,en-TK',
				'fipsCode' 	=> 'TL',
				'area' 		=> '10.0',
				'code' 		=> 'TK',
				'currency'	=> 'NZD',
			],

		220 =>[
				'country' 	=> 'East Timor',
				'continent' => 'Oceania',
				'capital' 	=> 'Dili',
				'language' 	=> 'tet,pt-TL,id,en',
				'fipsCode' 	=> 'TT',
				'area' 		=> '15007.0',
				'code' 		=> 'TL',
				'currency' 	=> 'USD',
			],

		221 =>[
				'country' 	=> 'Turkmenistan',
				'continent' => 'Asia',
				'capital' 	=> 'Ashgabat',
				'language' 	=> 'tk,ru,uz',
				'fipsCode' 	=> 'TX',
				'area' 		=> '488100.0',
				'code' 		=> 'TM',
				'currency' 	=> 'TMT',
			],

		222 =>[
				'country' 	=> 'Tunisia',
				'continent' => 'Africa',
				'capital' 	=> 'Tunis',
				'language' 	=> 'ar-TN,fr',
				'fipsCode' 	=> 'TS',
				'area' 		=> '163610.0',
				'code' 		=> 'TN',
				'currency' 	=> 'TND',
			],

		223 =>[
				'country' 	=> 'Tonga',
				'continent' => 'Oceania',
				'capital' 	=> 'Nuku\'alofa',
				'language' 	=> 'to,en-TO',
				'fipsCode' 	=> 'TN',
				'area' 		=> '748.0',
				'code' 		=> 'TO',
				'currency' 	=> 'TOP',
			],

		224 =>[
				'country' 	=> 'Turkey',
				'continent' => 'Asia',
				'capital' 	=> 'Ankara',
				'language' 	=> 'tr-TR,ku,diq,az,av',
				'fipsCode' 	=> 'TU',
				'area' 		=> '780580.0',
				'code' 		=> 'TR',
				'currency' 	=> 'TRY',
			],

		225 =>[
				'country' 	=> 'Trinidad and Tobago',
				'continent' => 'North America',
				'capital' 	=> 'Port of Spain',
				'language' 	=> 'en-TT,hns,fr,es,zh',
				'fipsCode' 	=> 'TD',
				'area' 		=> '5128.0',
				'code' 		=> 'TT',
				'currency' 	=> 'TTD',
			],

		226 =>[
				'country' 	=> 'Tuvalu',
				'continent' => 'Oceania',
				'capital' 	=> 'Funafuti',
				'language' 	=> 'tvl,en,sm,gil',
				'fipsCode' 	=> 'TV',
				'area' 		=> '26.0',
				'code' 		=> 'TV',
				'currency' 	=> 'AUD',
			],

		227 =>[
				'country' 	=> 'Taiwan',
				'continent' => 'Asia',
				'capital' 	=> 'Taipei',
				'language' 	=> 'zh-TW,zh,nan,hak',
				'fipsCode' 	=> 'TW',
				'area' 		=> '35980.0',
				'code' 		=> 'TW',
				'currency' 	=> 'TWD',
			],

		228 =>[
				'country' 	=> 'Tanzania',
				'continent' => 'Africa',
				'capital' 	=> 'Dodoma',
				'language' 	=> 'sw-TZ,en,ar',
				'fipsCode' 	=> 'TZ',
				'area' 		=> '945087.0',
				'code' 		=> 'TZ',
				'currency' 	=> 'TZS',
			],

		229 =>[
				'country' 	=> 'Ukraine',
				'continent' => 'Europe',
				'capital' 	=> 'Kiev',
				'language' 	=> 'uk,ru-UA,rom,pl,hu',
				'fipsCode' 	=> 'UP',
				'area' 		=> '603700.0',
				'code' 		=> 'UA',
				'currency' 	=> 'UAH',
			],

		230 =>[
				'country' 	=> 'Uganda',
				'continent' => 'Africa',
				'capital' 	=> 'Kampala',
				'language' 	=> 'en-UG,lg,sw,ar',
				'fipsCode' 	=> 'UG',
				'area' 		=> '236040.0',
				'code' 		=> 'UG',
				'currency' 	=> 'UGX',
			],

		231 =>[
				'country' 	=> 'U.S. Minor Outlying Islands',
				'continent' => 'Oceania',
				'capital' 	=> '',
				'fipsCode' 	=> '',
				'area' 		=> '0.0',
				'code' 		=> 'UM',
				'currency' 	=> 'USD',
			],

		232 =>[
				'country' 	=> 'United States',
				'continent' => 'North America',
				'capital' 	=> 'Washington',
				'language' 	=> 'en-US,es-US,haw,fr',
				'fipsCode' 	=> 'US',
				'area' 		=> '9629091.0',
				'code' 		=> 'US',
				'currency' 	=> 'USD',
			],

		233 =>[
				'country' 	=> 'Uruguay',
				'continent' => 'South America',
				'capital' 	=> 'Montevideo',
				'language' 	=> 'es-UY',
				'fipsCode' 	=> 'UY',
				'area' 		=> '176220.0',
				'code' 		=> 'UY',
				'currency' 	=> 'UYU',
			],

		234 =>[
				'country' 	=> 'Uzbekistan',
				'continent' => 'Asia',
				'capital' 	=> 'Tashkent',
				'language' 	=> 'uz,ru,tg',
				'fipsCode' 	=> 'UZ',
				'area' 		=> '447400.0',
				'code' 		=> 'UZ',
				'currency' 	=> 'UZS',
			],

		235 =>[
				'country' 	=> 'Vatican City',
				'continent' => 'Europe',
				'capital' 	=> 'Vatican City',
				'language' 	=> 'la,it,fr',
				'fipsCode' 	=> 'VT',
				'area' 		=> '0.44',
				'code' 		=> 'VA',
				'currency' 	=> 'EUR',
			],

		236 =>[
				'country' 	=> 'Saint Vincent and the Grenadines',
				'continent' => 'North America',
				'capital' 	=> 'Kingstown',
				'language' 	=> 'en-VC,fr',
				'fipsCode' 	=> 'VC',
				'area' 		=> '389.0',
				'code' 		=> 'VC',
				'currency' 	=> 'XCD',
			],

		237 =>[
				'country' 	=> 'Venezuela',
				'continent' => 'South America',
				'capital' 	=> 'Caracas',
				'language' 	=> 'es-VE',
				'fipsCode' 	=> 'VE',
				'area' 		=> '912050.0',
				'code' 		=> 'VE',
				'currency' 	=> 'VEF',
			],

		238 =>[
				'country' 	=> 'British Virgin Islands',
				'continent' => 'North America',
				'capital' 	=> 'Road Town',
				'language' 	=> 'en-VG',
				'fipsCode' 	=> 'VI',
				'area' 		=> '153.0',
				'code' 		=> 'VG',
				'currency' 	=> 'USD',
			],

		239 =>[
				'country' 	=> 'U.S. Virgin Islands',
				'continent' => 'North America',
				'capital' 	=> 'Charlotte Amalie',
				'language' 	=> 'en-VI',
				'fipsCode' 	=> 'VQ',
				'area' 		=> '352.0',
				'code' 		=> 'VI',
				'currency' 	=> 'USD',
			],

		240 =>[
				'country' 	=> 'Vietnam',
				'continent' => 'Asia',
				'capital' 	=> 'Hanoi',
				'language' 	=> 'vi,en,fr,zh,km',
				'fipsCode' 	=> 'VM',
				'area' 		=> '329560.0',
				'code' 		=> 'VN',
				'currency' 	=> 'VND',
			],

		241 =>[
				'country' 	=> 'Vanuatu',
				'continent' => 'Oceania',
				'capital' 	=> 'Port Vila',
				'language' 	=> 'bi,en-VU,fr-VU',
				'fipsCode' 	=> 'NH',
				'area' 		=> '12200.0',
				'code' 		=> 'VU',
				'currency' 	=> 'VUV',
			],

		242 =>[
				'country' 	=> 'Wallis and Futuna',
				'continent' => 'Oceania',
				'capital' 	=> 'Mata-Utu',
				'language' 	=> 'wls,fud,fr-WF',
				'fipsCode' 	=> 'WF',
				'area' 		=> '274.0',
				'code' 		=> 'WF',
				'currency' 	=> 'XPF',
			],

		243 =>[
				'country' 	=> 'Samoa',
				'continent' => 'Oceania',
				'capital' 	=> 'Apia',
				'language' 	=> 'sm,en-WS',
				'fipsCode' 	=> 'WS',
				'area' 		=> '2944.0',
				'code' 		=> 'WS',
				'currency' 	=> 'WST',
			],

		244 =>[
				'country' 	=> 'Kosovo',
				'continent' => 'Europe',
				'capital' 	=> 'Pristina',
				'language' 	=> 'sq,sr',
				'fipsCode' 	=> 'KV',
				'area' 		=> '10908.0',
				'code' 		=> 'XK',
				'currency' 	=> 'EUR',
			],

		245 =>[
				'country' 	=> 'Yemen',
				'continent' => 'Asia',
				'capital' 	=> 'Sanaa',
				'language' 	=> 'ar-YE',
				'fipsCode' 	=> 'YM',
				'area' 		=> '527970.0',
				'code' 		=> 'YE',
				'currency' 	=> 'YER',
			],

		246 =>[
				'country' 	=> 'Mayotte',
				'continent' => 'Africa',
				'capital' 	=> 'Mamoudzou',
				'language' 	=> 'fr-YT',
				'fipsCode' 	=> 'MF',
				'area' 		=> '374.0',
				'code' 		=> 'YT',
				'currency' 	=> 'EUR',
			],

		247 =>[
				'country' 	=> 'South Africa',
				'continent' => 'Africa',
				'capital' 	=> 'Pretoria',
				'language' 	=> 'zu,xh,af,nso,en-ZA,tn,st,ts,ss,ve,nr',
				'fipsCode' 	=> 'SF',
				'area' 		=> '1219912.0',
				'code' 		=> 'ZA',
				'currency' 	=> 'ZAR',
			],

		248 =>[
				'country' => 'Zambia',
				'continent' => 'Africa',
				'capital' => 'Lusaka',
				'language' => 'en-ZM,bem,loz,lun,lue,ny,toi',
				'fipsCode' => 'ZA',
				'area' => '752614.0',
				'code' => 'ZM',
				'currency' => 'ZMW',
			],

		249 =>[
				'country' 	=> 'Zimbabwe',
				'continent' => 'Africa',
				'capital' 	=> 'Harare',
				'language' 	=> 'en-ZW,sn,nr,nd',
				'fipsCode' 	=> 'ZI',
				'area' 		=> '390580.0',
				'code' 		=> 'ZW',
				'currency' 	=> 'ZWL',
			],

	];

?>	